#!/usr/bin/env python3
"""Convert 完美图标/音乐 PNGs to 1bpp C arrays — 一比一, 不做任何裁剪/缩放.

用户要求: 直接用原始图标尺寸, 不调整图片. 每个图标按其 PNG 原始像素逐点转,
bit=1 为黑(符号), bit=0 为白(背景/不绘制). 生成头文件含各图标的 W/H 宏.
"""
from PIL import Image
import os

SRC_DIR = "/Users/linit/Desktop/完美图标/音乐"
OUT = "/Users/linit/AI项目/LinTOS0.5/components/os/pages/mp3_icons_auto.h"

ITEMS = [
    ("mp3ic_loop_single", "单曲循环.png"),
    ("mp3ic_loop_list",   "列表循环.png"),
    ("mp3ic_loop_random", "随机播放.png"),
    ("mp3ic_prev",        "上首歌_副本.png"),
    ("mp3ic_play",        "播放.png"),
    ("mp3ic_pause",       "暂停.png"),
    ("mp3ic_next",        "下首歌.png"),
    ("mp3ic_vol",         "音量.png"),
]


def to_1bpp(src):
    """原尺寸逐像素: 透明或白 → 0, 黑(暗) → 1. 返回 (w, h, rows)."""
    img = Image.open(src).convert("RGBA")
    w, h = img.size
    px = img.load()
    bw = [[0] * w for _ in range(h)]
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a < 128:
                continue                 # 透明 → 不绘制 (0)
            if r < 128 and g < 128 and b < 128:
                bw[y][x] = 1             # 黑/暗 → 符号 (1)
    rows = []
    for y in range(h):
        for x in range(w):
            if x % 8 == 0:
                byte = 0
            if bw[y][x]:
                byte |= (1 << (7 - (x % 8)))
            if x % 8 == 7 or x == w - 1:
                rows.append(byte)
    return w, h, rows


def main():
    lines = []
    lines.append("/* Auto-generated by gen_mp3_iconts.py — 完美图标/音乐 原始尺寸一比一 1bpp. */")
    specs = []
    for name, fname in ITEMS:
        w, h, data = to_1bpp(os.path.join(SRC_DIR, fname))
        nbytes = len(data)
        specs.append((name, w, h))
        lines.append("")
        lines.append("#define %s_W %d" % (name, w))
        lines.append("#define %s_H %d" % (name, h))
        lines.append("static const uint8_t %s[%d] = {" % (name, nbytes))
        for i in range(0, nbytes, 12):
            vals = ", ".join("0x%02X" % b for b in data[i:i + 12])
            lines.append("    " + vals + ",")
        lines.append("};")
        print("  %s <- %s : %dx%d, %d bytes" % (name, fname, w, h, nbytes))
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("Wrote " + OUT)


if __name__ == "__main__":
    main()